# Generated by Django 3.1.1 on 2020-09-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Home Appliances', 'Home Appliances'), ('Food and groceries', 'Food and groceries'), ('outdoor', 'outdoor'), ('Other', 'Other')], default='Other', max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
